server:
  port: 520
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
spring:
  profiles:
    active: dev
  application:
    name: dear-agent
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  ai:
    openai:
      api-key: xxx
      base-url: https://dashscope.aliyuncs.com/compatible-mode/
      chat:
        options:
          model: glm-5
          temperature: 0.7
          maxTokens: 50000
      embedding:
        base-url: https://dashscope.aliyuncs.com/compatible-mode/
        api-key: xxx
        options:
          model: text-embedding-v4
          dimensions: 1024
    deepseek:
      api-key: xxx
    minimax:
      api-key: xxx
    zhipuai:
      api-key: xxx
    ollama:
      base-url: http://127.0.0.1:11434
      chat:
        options:
          model: deepseek-r1:7b
    anthropic:
      api-key: xxx
  datasource:
    url: jdbc:mysql://${mysql.host:localhost}:3306/dear-agent?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: ${mysql.username:root}
    password: ${mysql.password:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000
  data:
    redis:
      host: ${redis.host:localhost}
      port: ${redis.port:6379}
      database: ${redis.database:1}
      timeout: 5s
      password: ${redis.password}
  redis:
    redisson:
      config: |
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          subscriptionsPerConnection: 5
          clientName: null
          address: "redis://${redis.host:localhost}:${redis.port:6379}"
          password: ${redis.password}
          database: ${redis.database:1}
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          connectionMinimumIdleSize: 24
          connectionPoolSize: 64
          dnsMonitoringInterval: 5000
        threads: 16
        nettyThreads: 32
        codec: !<org.redisson.codec.JsonJacksonCodec> {}
        transportMode: "NIO"
  mybatis-plus:
    mapper-locations: classpath:mapper/*.xml

jetcache:
  statIntervalMinutes: 0
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson2
      limit: 100
  remote:
    default:
      type: redisson
      keyConvertor: fastjson2
      broadcastChannel: ${spring.application.name}
      keyPrefix: ${spring.application.name}
      valueEncoder: java
      valueDecoder: java
      defaultExpireInMillis: 5000

elasticsearch:
  host: http://127.0.0.1:9201
  api-key: Z0VGd1ZaNEJ4UXA4Y0VlYWZSZ2U6bi1KMXdvcW1UcXlrSThUOUwwOHh0QQ==
  dimensions: 1536

logging:
  level:
    com.roydon.dear: debug
    org.springframework.ai: debug
    io.modelcontextprotocol: debug
