server:
  port: 520
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
spring:
#  profiles:
#    active: dev
  application:
    name: dear-agent
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
  ai:
    openai:
      api-key: xxx
      base-url: https://dashscope.aliyuncs.com/compatible-mode/
      chat:
        options:
          model: glm-5
          temperature: 0.7
          maxTokens: 50000
      embedding:
        base-url: https://dashscope.aliyuncs.com/compatible-mode/
        api-key: xxx
        options:
          model: text-embedding-v4
          dimensions: 1024
    deepseek:
      api-key: xxx
    minimax:
      api-key: xxx
    zhipuai:
      api-key: xxx
    ollama:
      base-url: http://127.0.0.1:11434
      chat:
        options:
          model: deepseek-r1:7b
    anthropic:
      api-key: xxx
  datasource:
    url: jdbc:mysql://43.240.221.8:3306/dear-agent?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: roydon
    password: roydon#Mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000
  data:
    redis:
      host: 43.240.221.8
      port: 6379
      database: 23
      timeout: 5s
      password: roydon#Redis
  redis:
    redisson:
      config: |
        singleServerConfig:
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          password: roydon#Redis
          subscriptionsPerConnection: 5
          clientName: null
          address: "redis://43.240.221.8:6379"
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          connectionMinimumIdleSize: 24
          connectionPoolSize: 64
          database: 23
          dnsMonitoringInterval: 5000
        threads: 16
        nettyThreads: 32
        codec: !<org.redisson.codec.JsonJacksonCodec> {}
        transportMode: "NIO"
  mybatis-plus:
    mapper-locations: classpath:mapper/*.xml

minio:
  url: http://43.240.221.8:9000/
  accessKey: roydon
  secretKey: roydon#Minio
  bucketName: dear-agent
  endpoint: http://43.240.221.8:9000/


# Tavily 搜索引擎配置
#tavily:
#  api-key: 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
#  mcp-url: https://mcp.tavily.com/mcp/

jetcache:
  statIntervalMinutes: 0
  areaInCacheName: false
  local:
    default:
      type: caffeine
      keyConvertor: fastjson2
      limit: 100
  remote:
    default:
      type: redisson
      keyConvertor: fastjson2
      broadcastChannel: ${spring.application.name}
      keyPrefix: ${spring.application.name}
      valueEncoder: java
      valueDecoder: java
      defaultExpireInMillis: 5000

logging:
  level:
    com.roydon.dear: debug
    org.springframework.ai: debug
    io.modelcontextprotocol: debug

#ai:
#  tts:
#    dashscope:
#      api-key: @dashscope.api.key@
#      base-url: https://dashscope.aliyuncs.com/api/v1/services/aigc/multimodal-generation/generation
#      model: qwen3-tts-flash
#      voice: Cherry
#      language-type: Chinese
# 阿里云 TTS 配置
alibaba:
  dashscope:
    tts:
      api-key: sk-cec420dff8b04f5f8aedf0d5e2c98a50
      base-url: https://dashscope.aliyuncs.com/api/v1/services/aigc/multimodal-generation/generation
      model: qwen3-tts-flash
      voice: Cherry
      language-type: Chinese
