server:
  port: 520
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
spring:
#  profiles:
#    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  ai:
    openai:
      api-key: @dashscope.api.key@
      base-url: https://dashscope.aliyuncs.com/compatible-mode/
      chat:
        options:
          model: glm-5
          temperature: 0.7
          maxTokens: 50000
      embedding:
        base-url: https://dashscope.aliyuncs.com/compatible-mode/
        api-key: @dashscope.api.key@
        options:
          model: text-embedding-v4
          dimensions: 1024
#      语音模型，提供 dashscope、ollama、openai等
#      audio:
#        speech:
#          api-key: @dashscope.api.key@
#          base-url: https://dashscope.aliyuncs.com/compatible-mode/
#          options:
#            model: cosyvoice-v3-flash
#            voice: xiaoyuan
#            response-format: mp3
#            speed: 1.0
#            sample-rate: 22050
#            volume: 50
#            rate: 1                     # 语速：0.5-2.0
  datasource:
    url: jdbc:mysql://43.240.221.8:3306/dear-agent?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: roydon
    password: roydon#Mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 60000
      connection-timeout: 30000
      max-lifetime: 1800000
  data:
    redis:
      host: 43.240.221.8
      port: 6379
      database: 23
      timeout: 5s
      password: roydon#Redis
  mybatis-plus:
    mapper-locations: classpath:mapper/*.xml

minio:
  url: http://127.0.0.1:9000/
  accessKey: roydon
  secretKey: roydon#Minio
  bucketName: dear-agent
  endpoint: http://127.0.0.1:9000/


# Tavily 搜索引擎配置
#tavily:
#  api-key: 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
#  mcp-url: https://mcp.tavily.com/mcp/

logging:
  level:
    com:
      roydon:
        dear: debug
    org:
      springframework:
        ai: debug
    io:
      modelcontextprotocol:
        client: ERROR


#ai:
#  tts:
#    dashscope:
#      api-key: @dashscope.api.key@
#      base-url: https://dashscope.aliyuncs.com/api/v1/services/aigc/multimodal-generation/generation
#      model: qwen3-tts-flash
#      voice: Cherry
#      language-type: Chinese
# 阿里云 TTS 配置
alibaba:
  dashscope:
    tts:
      api-key: sk-cec420dff8b04f5f8aedf0d5e2c98a50
      base-url: https://dashscope.aliyuncs.com/api/v1/services/aigc/multimodal-generation/generation
      model: qwen3-tts-flash
      voice: Cherry
      language-type: Chinese
